[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hydra_example_anchor = "Xyj597GykzwSu44muqNHtYs2aKUgm9ydNoHNySTDFs5"

[programs.localnet]
hydra_example_anchor = "rgMuTEnEYWEK3EzqH9MkFthU9shDAPLgZX7dztEbBf4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/hydra-example-anchor/Cargo.toml --test mollusk -- --nocapture"

[hooks]
